---
title: "Variables"
author: "mia"
date: "2024-08-29"
output:
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
library(tidyverse)
library(here)      
library(readxl)    
library(janitor)   
library(stringr)   
library(tidyr)     
library(dplyr)
library(knitr)
```
# Variable Selection
```{r, message=FALSE}
raw_bp <- read.csv(here("ZIPallFiles","AHSnpa11bp.csv"), header=TRUE)
raw_bb <- read.csv(here("ZIPallFiles","AHSnpa11bb.csv"), header=TRUE)
bp_bb <- inner_join(raw_bp, raw_bb, by = "ABSPID")

raw_bsp <- read.csv(here("ZIPallFiles","inp13bsp.csv"), header=TRUE)
raw_bcn <- read.csv(here("ZIPallFiles","inp13bcn.csv"), header=TRUE)
bsp_bcn <- inner_join(raw_bsp, raw_bcn, by = "ABSHID")
bsp_bcn <- bsp_bcn %>%
  rename(ABSPID = ABSHID,AGEC =AGEEC)


X_all_File_variables <- read_excel("ZIPallFiles/_all.File.variables.xlsx", 
    sheet = "Variables", col_names = FALSE)

X_all_File_variables <- X_all_File_variables %>%
  rename(
    Survey = `...1`,
    Name = `...2`,
    VariableNames = `...3`,
    Description = `...4`
  ) %>%
  filter(Name %in% c("AHSnpa11bp", "AHSnpa11ba"))
```

```{r}
# Define the search term (excluding fat followed by ')')
search_terms <- c("sodium","potassium","fibre")

# Create a case-insensitive regex pattern
search_pattern <- paste0("(?i)", paste(search_terms, collapse = "|"))

# Filter variables based on the updated search term
Possible_Variables <- X_all_File_variables %>%
  filter(grepl(search_pattern, Description, perl = TRUE)) %>%
  select(VariableNames, Description) %>%
  distinct()
```

```{r}
columns_to_keep <- Possible_Variables$VariableNames

filtered_bp_bb <- bp_bb %>%
  select(any_of(columns_to_keep))

kept_columns_df <- Possible_Variables %>%
  filter(VariableNames %in% names(filtered_bp_bb))

kept_columns_df %>%
  kable(col.names = c("Variable Name", "Description"),
        caption = "Kept Variables and Their Descriptions") %>%
  print()
```

There are some variables that share the same Variable Name but different in their descriptions.

```{r}
# Create a case-insensitive regex pattern
search_pattern <- paste0("(?i)", paste(search_terms, collapse = "|"))

# Add a column to the filtered_rows that identifies the matching search term
kept_columns_df <- Possible_Variables %>%
  mutate(MatchingTerm = str_extract(tolower(Description), search_pattern)) %>%
  filter(VariableNames %in% names(filtered_bp_bb))
```

```{r}
group_counts <- kept_columns_df %>%
  filter(!is.na(MatchingTerm)) %>%
  group_by(MatchingTerm) %>%
  summarise(Count = n(), .groups = 'drop') %>%
  arrange(MatchingTerm)

group_counts %>%
  kable(col.names = c("Matching Term", "Count"),
        caption = "Count of Entries for Each Matching Term") %>%
  print()
```

```{r}
grouped_output <- kept_columns_df %>%
  filter(!is.na(MatchingTerm)) %>%  # Ensure there are no NA values in MatchingTerm
  arrange(MatchingTerm) %>%
  select(MatchingTerm, VariableNames, Description)

grouped_output %>%
  kable(col.names = c("Matching Term", "Variable Name", "Description"),
        caption = "Kept Variables and Their Descriptions Grouped by Matching Terms") %>%
  print()
```

```{r}
Data1 <- bp_bb %>%
  select(
    ABSPID, HYPBC,
    AGEC, SEX, BMISC, SYSTOL, DIASTOL,
    POTAST1, POTAST2, SODIUMT1, SODIUMT2
  ) %>%
  mutate(
    HYPBC = as.factor(HYPBC),
    SEX = as.factor(SEX),
    BMISC = na_if(na_if(BMISC, 99), 98),
    SYSTOL = na_if(na_if(na_if(SYSTOL,0),998),999),
    DIASTOL = na_if(na_if(na_if(DIASTOL,0),998),999),
    POTAST = (POTAST1 + POTAST2) / 2, 
    SODIUMT = (SODIUMT1 + SODIUMT2) / 2
    ) %>%
  filter(AGEC >= 18, HYPBC == 5) %>%
  select(ABSPID, HYPBC, 
         AGEC, SEX, BMISC, 
         SYSTOL, DIASTOL, 
         POTAST, SODIUMT)

summary(Data1)
```

```{r}
Data2 <- bsp_bcn %>%
  select(
    ABSPID, ICD10ME,
    AGEC, SEX, BMISC, SYSTOL, DIASTOL,
    POTAST1, POTAST2, SODIUMT1, SODIUMT2
  ) %>%
  mutate(
    ICD10ME = as.factor(ICD10ME),
    SEX = as.factor(SEX),
    BMISC = na_if(na_if(BMISC, 99), 98),
    SYSTOL = na_if(na_if(na_if(SYSTOL,0),998),999),
    DIASTOL = na_if(na_if(na_if(DIASTOL,0),998),999),
    POTAST = (POTAST1 + POTAST2) / 2, 
    SODIUMT = (SODIUMT1 + SODIUMT2) / 2
    ) %>%
  filter(AGEC >= 18, !ICD10ME %in% c(7, 20)) %>%
  select(ABSPID, ICD10ME, 
         AGEC, SEX, BMISC, 
         SYSTOL, DIASTOL, 
         POTAST, SODIUMT)

summary(Data2)
```

```{r}
summary <- bind_rows(Data1, Data2)
summary(summary)
```

```{r}
bsp_bcn$POTAST1
```